version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11  # CircleCI's official Python image
    working_directory: ~/repo

    steps:
      - checkout  # pulls your code
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run migrations (SQLite)
          command: python /src/manage.py migrate
      - run:
          name: Run tests
          command: python /src/manage.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
